export const CREATE_INTERNSHIP_REQUEST = "CREATE_INTERNSHIP_REQUEST"
export const CREATE_INTERNSHIP_SUCCESS = "CREATE_INTERNSHIP_SUCCESS"
export const CREATE_INTERNSHIP_ERROR = "CREATE_INTERNSHIP_ERROR"
export const CREATE_INTERNSHIP_RESET = "CREATE_INTERNSHIP_RESET"

