export const EMPLOYER_LOGIN_REQUEST = "EMPLOYER_LOGIN_REQUEST"
export const EMPLOYER_LOGIN_SUCCESS = "EMPLOYER_LOGIN_SUCCESS"
export const EMPLOYER_LOGIN_ERROR = "EMPLOYER_LOGIN_ERROR"
export const EMPLOYER_LOGIN_RESET = "EMPLOYER_LOGIN_RESET"

export const EMPLOYER_LOGOUT = 'EMPLOYER_LOGOUT'
