export const INTERN_LOGIN_REQUEST = "INTERN_LOGIN_REQUEST";
export const INTERN_LOGIN_SUCCESS = "INTERN_LOGIN_SUCCESS";
export const INTERN_LOGIN_ERROR = "INTERN_LOGIN_ERROR";
export const INTERN_LOGIN_RESET = "INTERN_LOGIN_RESET";
export const INTERN_LOGOUT = "INTERN_LOGOUT";
