export const RETRIEVE_INTERNSHIPS_REQUEST = 'RETRIEVE_INTERNSHIPS_REQUEST'
export const RETRIEVE_INTERNSHIPS_SUCCESS = 'RETRIEVE_INTERNSHIPS_SUCCESS'
export const RETRIEVE_INTERNSHIPS_ERROR = 'RETRIEVE_INTERNSHIPS_ERROR'
export const RETRIEVE_INTERNSHIPS_RESET = 'RETRIEVE_INTERNSHIPS_RESET'

export const APPLY_INTERNSHIPS_REQUEST = 'APPLY_INTERNSHIPS_REQUEST'
export const APPLY_INTERNSHIPS_SUCCESS = 'APPLY_INTERNSHIPS_SUCCESS'
export const APPLY_INTERNSHIPS_ERROR = 'APPLY_INTERNSHIPS_ERROR'
export const APPLY_INTERNSHIPS_RESET = 'APPLY_INTERNSHIPS_RESET'