# Generated by Django 4.0.2 on 2022-02-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_details', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_is_mentored', models.BooleanField(default=False)),
                ('project_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_description', models.TextField(blank=True, null=True)),
                ('internship_compensation', models.IntegerField(blank=True, null=True)),
                ('internship_location', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_hard_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_soft_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_learning_outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_industry', models.TextField(blank=True, null=True)),
                ('internship_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField()),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
