# Generated by Django 4.0.2 on 2022-02-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_employerprofile_is_intern_internprofile_is_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_hard_skills',
            field=models.TextField(null=True),
        ),
    ]
