# Generated by Django 4.0.2 on 2022-02-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_internprofile_education'),
        ('base', '0004_internship_enrolled_intern_project_enrolled_intern'),
    ]

    operations = [
    ]
