export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR"
export const CREATE_PROJECT_RESET = "CREATE_PROJECT_RESET"

