export const EMPLOYER_REGISTER_REQUEST = "EMPLOYER_REGISTER_REQUEST"
export const EMPLOYER_REGISTER_SUCCESS = "EMPLOYER_REGISTER_SUCCESS"
export const EMPLOYER_REGISTER_ERROR = "EMPLOYER_REGISTER_ERROR"
export const EMPLOYER_REGISTER_RESET = "EMPLOYER_REGISTER_RESET"
