export const RETRIEVE_PROJECTS_REQUEST = 'RETRIEVE_PROJECTS_REQUEST'
export const RETRIEVE_PROJECTS_SUCCESS = 'RETRIEVE_PROJECTS_SUCCESS'
export const RETRIEVE_PROJECTS_ERROR = 'RETRIEVE_PROJECTS_ERROR'
export const RETRIEVE_PROJECTS_RESET = 'RETRIEVE_PROJECTS_RESET'

export const APPLY_PROJECTS_REQUEST = 'APPLY_PROJECTS_REQUEST'
export const APPLY_PROJECTS_SUCCESS = 'APPLY_PROJECTS_SUCCESS'
export const APPLY_PROJECTS_ERROR = 'APPLY_PROJECTS_ERROR'
export const APPLY_PROJECTS_RESET = 'APPLY_PROJECTS_RESET'