export const RETRIEVE_COURSES_REQUEST = 'RETRIEVE_COURSES_REQUEST'
export const RETRIEVE_COURSES_SUCCESS = 'RETRIEVE_COURSES_SUCCESS'
export const RETRIEVE_COURSES_ERROR = 'RETRIEVE_COURSES_ERROR'
export const RETRIEVE_COURSES_RESET = 'RETRIEVE_COURSES_RESET'