export const INTERN_REGISTER_REQUEST = "INTERN_REGISTER_REQUEST";
export const INTERN_REGISTER_SUCCESS = "INTERN_REGISTER_SUCCESS";
export const INTERN_REGISTER_ERROR = "INTERN_REGISTER_ERROR";
export const INTERN_REGISTER_RESET = "INTERN_REGISTER_RESET";
