export const RETRIEVE_DASHBOARD_REQUEST = "RETRIEVE_DASHBOARD_REQUEST";
export const RETRIEVE_DASHBOARD_SUCCESS = "RETRIEVE_DASHBOARD_SUCCESS";
export const RETRIEVE_DASHBOARD_ERROR = "RETRIEVE_DASHBOARD_ERROR";
